// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0iJEVuuJ4ZBqmLe-3rqF7SPEHyiDF2EY',
    appId: '1:280280376704:web:51c2e9f6674bc9b26ecd65',
    messagingSenderId: '280280376704',
    projectId: 'omar-chat-app-4db21',
    authDomain: 'omar-chat-app-4db21.firebaseapp.com',
    storageBucket: 'omar-chat-app-4db21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChiDEIiO1Oz7_3e4J0V1D08vX8WOjPRB4',
    appId: '1:280280376704:android:8cf420b6f804e2906ecd65',
    messagingSenderId: '280280376704',
    projectId: 'omar-chat-app-4db21',
    storageBucket: 'omar-chat-app-4db21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwLpvwDIWNJ_ua1V7ikV8tsut_XApDs4',
    appId: '1:280280376704:ios:5d9c6d5bc70e06456ecd65',
    messagingSenderId: '280280376704',
    projectId: 'omar-chat-app-4db21',
    storageBucket: 'omar-chat-app-4db21.appspot.com',
    iosBundleId: 'com.example.omarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwLpvwDIWNJ_ua1V7ikV8tsut_XApDs4',
    appId: '1:280280376704:ios:5d9c6d5bc70e06456ecd65',
    messagingSenderId: '280280376704',
    projectId: 'omar-chat-app-4db21',
    storageBucket: 'omar-chat-app-4db21.appspot.com',
    iosBundleId: 'com.example.omarChatApp',
  );
}
